stages:
  - build

build-app:
  stage: build
  image: ubuntu:latest
  script:
    - apt-get update -y
    - apt-get install -y curl
    - curl -sL https://bun.sh/install | bash
    - bun install
    - bun run build
