stages:
  - build

build-app:
  stage: build
  image: ubuntu:latest
  script:
    - apt-get update -y
    - apt-get install -y curl
    - curl -sL https://deb.nodesource.com/setup_14.x | bash -
    - apt-get install -y nodejs
    - npm install -g bun
    - bun install
    - bun run build
