build websites:

    image: oven/bun:latest

    stages:
    - build

    build:
    stage: build
    script:
        - bun run build
        - bun run install 
    artifacts:
        paths:
        - public
