stages:
  - build

build-app:
  stage: build
  image: oven/bun:alpine
  script:
    - apk add --no-cache curl
    - curl -sL https://bun.sh/install | bash
    - source /root/.bashrc
    - bun install
    - bun run build
  artifacts:
    paths:
      - build/