build websites:

    image: oven/bun:latest

    stages:
    - build

    build:
    stage: build
    script:
        - bun install
        - bun run build
    artifacts:
        paths:
        - public
