name: My Workflow

on:
  push:
    branches:
      - developer

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Build app
        run: bun run build
      - name: Start app
        run: bun run start &
      - name: Wait for app to start
        run: sleep 10
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: My Artifacts
          path: /this works but stops on bun run start
